### ISSUE TITLE
Conform can't translate schema

### ISSUE THREAD

**Issue by GalaxyGorilla** [carosio/unimux#9]
I'm currently trying to update exrm to a newer version from bitwalkers repo. Also conform is updated to '0.16.0' as dependency. I get the following error message when I try 'mix conform.effective':

*\* (Conform.Schema.SchemaError) Invalid schema. Should be a keyword list containing :mappings and :translations keys.
    lib/conform/translate.ex:169: Conform.Translate.to_config/3
    lib/mix/tasks/conform.effective.ex:84: Mix.Tasks.Conform.Effective.do_run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2

I did not touch the config dir. Any suggestions to fix this?

**Comment by 0xAX** [comment]
Hello @GalaxyGorilla, I've fixed this bug (https://github.com/bitwalker/conform/commit/97723ee24b960e506bff557561d59cc95a09a56b) but seems that `exrm` didn't use this revision. Just tested it with your GalaxyGorilla/unimux repo and it works:

```
~/work/unimux (master) $ mix conform.effective
[exometer: [predefined: [{[:erlang, :system_info],
    {:function, :erlang, :system_info, [:"$dp"], :value,
     [:port_count, :process_count, :thread_pool_size]}, []},
   {[:erlang, :statistics],
    {:function, :erlang, :statistics, [:"$dp"], :value, [:run_queue]}, []},
   {[:erlang, :memory],
    {:function, :erlang, :memory, [:"$dp"], :value,
     [:total, :processes, :ets, :binary, :atom, :atom_used, :maximum]}, []}],
  report: [reporters: [exometer_report_graphite: [host: 'localhost', port: 2003,
     api_key: 'exometer']],
   subscribers: [{:exometer_report_graphite, [:erlang, :system_info],
     :port_count, 1000, true},
    {:exometer_report_graphite, [:erlang, :system_info], :process_count, 1000,
     true},
    {:exometer_report_graphite, [:erlang, :system_info], :thread_pool_size,
     1000, true},
    {:exometer_report_graphite, [:erlang, :statistics], :run_queue, 1000, true},
    {:exometer_report_graphite, [:erlang, :memory], :total, 2000, true},
    {:exometer_report_graphite, [:erlang, :memory], :processes, 2000, true},
    {:exometer_report_graphite, [:erlang, :memory], :ets, 2000, true},
    {:exometer_report_graphite, [:erlang, :memory], :binary, 2000, true},
    {:exometer_report_graphite, [:erlang, :memory], :atom, 2000, true},
    {:exometer_report_graphite, [:erlang, :memory], :atom_used, 2000, true},
    {:exometer_report_graphite, [:erlang, :memory], :maximum, 2000, true}]]],
 lager: [crash_log: 'false', handlers: 'false'],
 unimux: [listen: 'http://127.0.0.1:20001',
  routes: [{"APIPrefix1", 'http://127.0.0.1:8080'},
   {"APIPrefix2", 'http://127.0.0.1:8081'}]]]
```

I see that you updated `exrm` in your repo, try to set conform -> master there instead of 0.16.0

**Comment by GalaxyGorilla** [comment]
Thanks @0xAX ! I'll update the conform dependency and make a PR.

**Comment by 0xAX** [comment]
Ive tested only with local changes, let me know if there will be something wrong

**Comment by GalaxyGorilla** [comment]
I am testing this with Elixir 1.1.0-rc0 and I get

Unsupported URI format: http://127.0.0.1:20001
*\* (exit) 1
    (stdlib) erl_eval.erl:913: :erl_eval.try_clauses/8
    lib/conform/translate.ex:111: anonymous fn/5 in Conform.Translate.to_config/3
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/conform/translate.ex:81: Conform.Translate.to_config/3
    lib/mix/tasks/conform.effective.ex:90: Mix.Tasks.Conform.Effective.do_run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2

**Comment by 0xAX** [comment]
@GalaxyGorilla Which branch can I use for test? I've used your repo with master branch (Elixir version is 1.1.0-rc0) and I can't reproduce this case, `mix conform.effective` works good for me

**Comment by GalaxyGorilla** [comment]
@0xAX: These were local problems. All tests in https://github.com/carosio/unimux/pull/10 were running nice. Sorry for the noise and thanks for your help!
